title: "Vinitha Pukazh Bagya R"
description: "Senior Full Stack Developer | Portfolio"
baseurl: "" # leave as is if deploying at root
url: ""     # add your full domain when ready

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"

# Disable default theme UI elements
header:
  show_header: false
footer:
  links: []

defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: false
      sidebar:
        nav: false
      header:
        show_header: false
      show_date: false
      read_time: false
      comments: false
      share: false
      related: false

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache